[package]
name = "fixed_pool"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DouglasDwyer/fixed_pool"
readme = "README.md"
description = """
Fixed-size object pool with ownership and return semantics.
"""